module CatsHelper

def cat_breeds
  [
    ['Unknown / Other'],
    ['Abyssinian'],
    ['American Bobtail'],
    ['American Curl'],
    ['American Shorthair'],
    ['American Wirehair'],
    ['Balinese'],
    ['Bengal'],
    ['Birman'],
    ['Bombay'],
    ['British Shorthair'],
    ['Burmese'],
    ['Chartreux'],
    ['Chausie'],
    ['Colorpoint Shorthair'],
    ['Cornish Rex'],
    ['Devon Rex'],
    ['Egyptian Mau'],
    ['European Burmese'],
    ['Exotic'],
    ['Havana Brown'],
    ['Highlander'],
    ['Himalayan'],
    ['Japanese Bobtail'],
    ['Javanese'],
    ['Korat'],
    ['Kurilian Bobtail'],
    ['LaPerm'],
    ['Maine Coon'],
    ['Manx'],
    ['Manx (formerly Cymric)'],
    ['Munchkin'],
    ['Norwegian Forest Cat'],
    ['Ocicat'],
    ['Oriental'],
    ['Oriental Longhair'],
    ['Persian'],
    ['Peterbald'],
    ['Pixiebob'],
    ['RagaMuffin'],
    ['Ragdoll'],
    ['Russian Blue'],
    ['Savannah'],
    ['Scottish Fold'],
    ['Selkirk Rex'],
    ['Siamese'],
    ['Siberian'],
    ['Singapura'],
    ['Snowshoe'],
    ['Somali'],
    ['Sphynx'],
    ['Thai'],
    ['Tonkinese'],
    ['Toyger'],
    ['Turkish Angora'],
    ['Turkish Van']
  ]
end

end
