module DogsHelper

def dog_breeds
  [
    ['Unknown / Other'],
    ['Affenpinscher'],
    ['Afghan Hound'],
    ['Airedale Terrier'],
    ['Akita'],
    ['Alaskan Malamute'],
    ['Standard American Eskimo Dog'],
    ['Miniature American Eskimo Dog'],
    ['Toy American Eskimo Dog'],
    ['American Staffordshire Terrier'],
    ['American Water Spaniel'],
    ['Anatolian Shepherd Dog'],
    ['Australian Cattle Dog'],
    ['Australian Shepherd'],
    ['Australian Terrier'],
    ['Basenji'],
    ['Basset Hound'],
    ['Beagle'],
    ['Bearded Collie'],
    ['Beauceron'],
    ['Bedlington Terrier'],
    ['Belgian Malinois'],
    ['Belgian Sheepdog'],
    ['Belgian Tervuren'],
    ['Bernese Mountain Dog'],
    ['Bichon Frise'],
    ['Black and Tan Coonhound'],
    ['Black Russian Terrier'],
    ['Bloodhound'],
    ['Border Collie'],
    ['Border Terrier'],
    ['Borzoi'],
    ['Boston Terrier'],
    ['Bouvier des Flandres'],
    ['Boxer'],
    ['Briard'],
    ['Brittany'],
    ['Brussels Griffon'],
    ['Bulldog'],
    ['Bullmastiff'],
    ['Bull Terrier'],
    ['Cairn Terrier'],
    ['Canaan Dog'],
    ['Cardigan Welsh Corgi'],
    ['Cavalier King Charles Spaniel'],
    ['Chesapeake Bay Retriever'],
    ['Chihuahua'],
    ['Chinese Crested'],
    ['Chinese Shar-Pei'],
    ['Chow Chow'],
    ['Clumber Spaniel'],
    ['Cocker Spaniel'],
    ['Collie'],
    ['Curly-Coated Retriever'],
    ['Dachshund'],
    ['Dalmatian'],
    ['Dandie Dinmont Terrier'],
    ['Doberman Pinscher'],
    ['Dogue de Bordeaux'],
    ['English Cocker Spaniel'],
    ['English Foxhound'],
    ['English Setter'],
    ['English Springer Spaniel'],
    ['English Toy Spaniel'],
    ['Field Spaniel'],
    ['Finnish Spitz'],
    ['Flat-Coated Retriever'],
    ['French Bulldog'],
    ['German Pinscher'],
    ['German Shepherd Dog'],
    ['German Shorthaired Pointer'],
    ['German Wirehaired Pointer'],
    ['Giant Schnauzer'],
    ['Glen of Imaal Terrier'],
    ['Golden Retriever'],
    ['Gordon Setter'],
    ['Great Dane'],
    ['Greater Swiss Mountain Dog'],
    ['Great Pyrenees'],
    ['Greyhound'],
    ['Harrier'],
    ['Havanese'],
    ['Ibizan Hound'],
    ['Irish Setter'],
    ['Irish Terrier'],
    ['Irish Water Spaniel'],
    ['Irish Wolfhound'],
    ['Italian Greyhound'],
    ['Jack Russell Terrier'],
    ['Japanese Chin'],
    ['Keeshond'],
    ['Kerry Blue Terrier'],
    ['Komondor'],
    ['Kuvasz'],
    ['Labrador Retriever'],
    ['Lakeland Terrier'],
    ['Lhasa Apso'],
    ['Lowchen'],
    ['Maltese'],
    ['Standard Manchester Terrier'],
    ['Mastiff'],
    ['Miniature Bull Terrier'],
    ['Miniature Pinscher'],
    ['Miniature Poodle'],
    ['Miniature Schnauzer'],
    ['Neapolitan Mastiff'],
    ['Newfoundland'],
    ['Norfolk Terrier'],
    ['Norwegian Elkhound'],
    ['Norwich Terrier'],
    ['Nova Scotia Duck Tolling Retriever'],
    ['Old English Sheepdog'],
    ['Otterhound'],
    ['Papillon'],
    ['Parson Russell Terrier'],
    ['Pekingese'],
    ['Pembroke Welsh Corgi'],
    ['Petit Basset Griffon Vendeen'],
    ['Pharaoh Hound'],
    ['Plott'],
    ['Pointer'],
    ['Polish Lowland Sheepdog'],
    ['Pomeranian'],
    ['Portuguese Water Dog'],
    ['Pug'],
    ['Puli'],
    ['Rhodesian Ridgeback'],
    ['Rottweiler'],
    ['Saint Bernard'],
    ['Saluki'],
    ['Samoyed'],
    ['Schipperke'],
    ['Scottish Deerhound'],
    ['Scottish Terrier'],
    ['Sealyham Terrier'],
    ['Shetland Sheepdog'],
    ['Shiba Inu'],
    ['Shih Tzu'],
    ['Siberian Husky'],
    ['Silky Terrier'],
    ['Skye Terrier'],
    ['Smooth Fox Terrier'],
    ['Soft Coated Wheaten Terrier'],
    ['Spinone Italiano'],
    ['Staffordshire Bull Terrier'],
    ['Standard Poodle'],
    ['Standard Schnauzer'],
    ['Sussex Spaniel'],
    ['Swedish Vallhund'],
    ['Tibetan Mastiff'],
    ['Tibetan Spaniel'],
    ['Tibetan Terrier'],
    ['Toy Fox Terrier'],
    ['Toy Manchester Terrier'],
    ['Toy Poodle'],
    ['Vizsla'],
    ['Weimaraner'],
    ['Welsh Springer Spaniel'],
    ['Welsh Terrier'],
    ['West Highland White Terrier'],
    ['Whippet'],
    ['Wire Fox Terrier'],
    ['Wirehaired Pointing Griffon'],
    ['Yorkshire Terrier']
  ]
end

end
