module GerbilsHelper

def gerbil_breeds
  [
    ['Unknown / Other'],
    ['Persian Jird'],
    ['King Jird'],
    ['Indian Desert Jird'],
    ['Tamarisk'],
    ["Tristam's Jird"],
    ["Vinogradov's"],
    ["Cheng's Jird"],
    ["Sundevall's Jird"],
    ['Libyan Jird'],
    ['Chinese'],
    ["Buxton's Jird"],
    ["Shaw's Jird"],
    ['Mongolian'],
    ["Zarudny's Gerbil"],
    ['Charming Dipodil, Pleasant'],
    ["Botta's"],
    ['The Rock'],
    ["Wagner's Dipodil"],
    ['Black-Tufted'],
    ["Henley's Gerbil, Pigmy Dipodil"],
    ["James's"],
    ["Mackilligin's Dipodil"],
    ['Maghreb Gerbil, Greater Short-tailed Gerbil'],
    ['Mauritanian'],
    ['Mesopotamian'],
    ['Barfur'],
    ['Baluchistan'],
    ['Large Aden'],
    ['Least'],
    ['Little Red'],
    ['Khartoum'],
    ['Southern Pygmy Gerbil, Sand Gerbil'],
    ["Water's"],
    ["Simon's Dipodil, Lesser Short Tailed Gerbil"],
    ["Zakaria's"],
    ['Agag'],
    ["Allenby's"],
    ["Anderson's"],
    ['Swarthy'],
    ["Burton's"],
    ["Cheesman's"],
    ['Lesser Egyptian'],
    ['Indian Hairy-Footed'],
    ['Western'],
    ["Hoogstraal's"],
    ["Lataste's"],
    ['Sudan'],
    ['Occidental'],
    ['Pallid'],
    ['Cushioned'],
    ['Greater Egyptian'],
    ["Riggenback's"],
    ['Rosalinda'],
    ['Duprasi'],
    ['Bushy-Tailed Jird'],
    ['Sahel'],
    ['Congo'],
    ["Emin's"],
    ['The Slender'],
    ["Harrington's"],
    ['Lake Chad'],
    ["Petter's"],
    ['Senegal'],
    ["Böehm's gerbil, King gerbil"],
    ['Cape'],
    ['Highveld'],
    ['Gambian'],
    ['The Guinea'],
    ['Gorongoza'],
    ['Indian'],
    ['Bushveld'],
    ['The Black-Tailed'],
    ["Phillip's"],
    ["Pringle's"],
    ['Fringe-Tailed'],
    ["Kemp's"],
    ['Namib Paeba'],
    ["Setzer's Hairy-footed"],
    ['Dune Hairy-footed'],
    ['Brush-tailed Hairy-footed'],
    ['Fat Sand Rat'],
    ['Pale Sand Rat'],
    ['Somali Pygmy'],
    ['Short-tailed'],
    ["Brauer's"],
    ['Walo'],
    ['Great'],
    ["Przewalski's"]
  ]
end

end
