module HorsesHelper

def horse_breeds
  [
    ['Unknown / Other'],
    ['Abtenauer'],
    ['Abyssinian'],
    ['Aegidienberger'],
    ['Akhal-Teke'],
    ['Albanian'],
    ['Altai'],
    ['American Cream Draft'],
    ['American Indian'],
    ['American Paint'],
    ['American Quarter'],
    ['American Saddlebred'],
    ['American Warmblood'],
    ['Andalusian'],
    ['Andravida'],
    ['Anglo-Arabian'],
    ['Anglo-Arabo-Sardo'],
    ['Anglo-Kabarda'],
    ['Appaloosa'],
    ['AraAppaloosa'],
    ['Arabian'],
    ['Ardennes'],
    ['Arenberg-Nordkirchen'],
    ['Asturcón'],
    ['Augeron'],
    ['Australian Draught'],
    ['Australian Stock'],
    ['Austrian Warmblood'],
    ['Auvergne'],
    ['Auxois'],
    ['Azerbaijan']
    ['Azteca'],
    ['Baise'],
    ['Balearic'],
    ['Balikun'],
    ['Baluchi'],
    ["Ban'ei"],
    ['Banker'],
    ['Barb'],
    ['Bardigiano'],
    ['Basque Mountain'],
    ['Bavarian Warmblood'],
    ['Belgian'],
    ['Black Forest'],
    ['Blazer'],
    ['Boulonnais'],
    ['Brandenburger'],
    ['Brazilian Sport'],
    ['Breton'],
    ['Brumby'],
    ['Budyonny'],
    ['Burguete'],
    ['Byelorussian Harness'],
    ['Calabrese'],
    ['Camargue'],
    ['Camarillo White'],
    ['Campolina'],
    ['Canadian'],
    ['Canadian Pacer'],
    ['Carolina Marsh Tacky'],
    ['Caspian'],
    ['Castillonnais'],
    ['Catria'],
  ]
end

end
