module PoniesHelper

  def pony_breeds
    [
      ['American Walking'],
      ['Anadolu'],
      ['Australian'],
      ['Australian Riding'],
      ['Bali'],
      ['Bashkir'],
      ['Basuto'],
      ['Batak'],
      ['Boer'],
      ['Bosnian'],
      ['British Spotted'],
      ['Burmese'],
      ['Canadian Rustic'],
      ['Chincoteague'],
      ['Chinese Guoxia'],
      ['Coffin Bay'],
      ['Connemara'],
      ['Czechoslovakian Small Riding'],
      ['Dales'],
      ['Danish Sport'],
      ['Dartmoor'],
      ['Deli'],
      ['Dülmen'],
      ['Eriskay'],
      ['Esperia'],
      ['Exmoor'],
      ['Faroe'],
      ['Fell'],
      ['French Saddle'],
      ['Galician'],
      ['Garrano'],
      ['Gayoe'],
      ['German Riding'],
      ['Gotland'],
      ['Guizhou'],
      ['Hackney'],
      ['Highland'],
      ['Hokkaido'],
      ['Hucul'],
      ['Hunter'],
      ['Indian Country Bred'],
      ['Java'],
      ['Kerry Bog'],
      ['Landais'],
      ['Lijiang'],
      ['Lundy'],
      ['Manipuri'],
      ['Miyako'],
      ['Narym'],
      ['New Forest'],
      ['Newfoundland'],
      ['Noma'],
      ['Nooitgedacht'],
      ['Ob'],
      ['Peneia'],
      ['Petiso Argentino'],
      ['Pindos'],
      ['Poney Mousseye'],
      ['Pony of the Americas'],
      ['Pottok'],
      ['Quarter'],
      ['Sable Island'],
      ['Sandalwood'],
      ['Shetland'],
      ['Skyros'],
      ['Sumba and Sumbawa'],
      ['Tibetan'],
      ['Timor'],
      ['Tokara'],
      ['Vyatka'],
      ['Welara'],
      ['Welsh'],
      ['Western Sudan'],
      ['Zaniskari'],
      ['Žemaitukas']
    ]
  end

end
