module RabbitsHelper

def rabbit_breeds
  [
    ['Unknown / Other'],
    ['American'],
    ['American Fuzzy Lop'],
    ['American Sable'],
    ['English Angora'],
    ['French Angora'],
    ['Belgian Hare'],
    ['Beveren'],
    ['Britannia Petite'],
    ['California'],
    ["Champagne: D'Argent"],
    ['Checkered Giant'],
    ['Standard Chinchilla'],
    ['American Chinchilla'],
    ['Giant Chinchilla'],
    ['Cinnamon'],
    ["Creme D'Argent"],
    ['Dutch'],
    ['English Spot'],
    ['Flemish Giant'],
    ['Florida White'],
    ['Giant'],
    ['Harlequin'],
    ['Havana'],
    ['Himalayan'],
    ['Dwarf Hotot'],
    ['Hotot'],
    ['Jersey Wooly'],
    ['Lionhead'],
    ['Lilac'],
    ['English Lop'],
    ['French Lop'],
    ['Holland Lop'],
    ['American Fuzzy Lop'],
    ['Velveteen Lop'],
    ['Mini Lop'],
    ['Mini Plush Lop'],
    ['Netherland Dwarf'],
    ['New Zealand'],
    ['Palomino'],
    ['Polish'],
    ['Mini Plush Lop'],
    ['Rex'],
    ['Mini Rex'],
    ['Rhinelander'],
    ['Satin'],
    ['Mini Satin'],
    ['Stain Angora'],
    ['Silver Fox'],
    ['Silver'],
    ['Silver Marten'],
    ['Tan'],
    ['Velveteen Lop']
  ]
end

end
