source 'https://rubygems.org'


gem 'rails', '4.1.1'
# database
gem 'mysql2', group: :development
gem 'pg', group: :production

gem 'sass-rails', '~> 4.0.3'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 2.0'

gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'spring',        group: :development

gem 'paperclip', "~> 4.1"
gem 'haml-rails'
gem 'cancan'
gem 'workflow'
gem 'letter_opener', :group => :development
gem 'quiet_assets', :group => :development
gem 'nested_form'
gem 'devise'
gem 'jquery-ui-rails'
gem 'kaminari'
gem 'passport'
gem 'geocoder'
gem 'mapbox-rails'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'gmaps4rails'
gem 'twilio-ruby'
gem 'social-buttons', '~>0.3'
gem "paperclip-dropbox", ">= 1.1.7"