source 'https://rubygems.org'
gem 'sinatra'

#This is our database adapter
gem 'mysql'
#This will make it so I don't have to restart my server all of the time
gem 'shotgun'
#This is a console gem. IRB on CRACK
gem 'tux'

#This will connect our application to our database
gem 'data_mapper'
#This is our adapter for our data_mapper
gem 'dm-mysql-adapter'